### ISSUE TITLE
Cannot read property 'conn' of undefined

### ISSUE THREAD

**Issue by abidRahim** [weilandia/use-action-cable#2]
This is my implementation of `useActionCable`, after wrapping the component with `<ActionCableProvider>`

```
const channelParams = { channel: 'VehicleChannel', id: someId };
  const channelHandlers = {
    received(data) {
      console.log(JSON.parse(data));
    },
    connected() {
      console.log('Connected');
    },
    disconnected() {
      console.log('Disconnected');
    }
  };
  useActionCable(channelParams, channelHandlers);
```

However, the browser throws the following error

![Screenshot 2019-11-28 at 4 22 05 PM](https://user-images.githubusercontent.com/25589552/69801719-dff51380-11fd-11ea-8daf-d367b5be2d4b.png)

I guess, it needs to be type defined

**Comment by weilandia** [comment]
@abidRahim which versions of react and use-action-cable are you using?

Based on the stack trace, I'm guessing it's an old version of react -- This lib requires 16.8+.  I see a similar issue linked below:

https://github.com/facebook/react/issues/16224

Let me know if that's not the case and we can dig into it further.

**Comment by weilandia** [comment]
No response, closing for cleanup.  Feel free to reopen.
